title: "High in the Flight Sim Sky"
description: "Microsoft Flight Simulator 2020/2024 videos, tutorials, and adventures."
baseurl: ""
url: "https://highintheflightsimsky.nl"

collections:
  videos:
    output: true
    permalink: /videos/:slug/
  series:
    output: true
    permalink: /series/:slug/