title: High in the flight sim sky
description: Site containing information about Flight Simulator 2020
show_downloads: false

#baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://highintheflightsimsky.nl" # change this to the base hostname & protocol for your site


google_analytics: UA-177201520-1

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Johan Veldhuis
image: /thumbnail-jumbo.png
twitter:
  username: highinthefssky

plugins:
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5

target-blank:
    rel: nofollow

header_page_refs: ['about']

collections:
  category:
    output: true